DROP TABLE CHATTING CASCADE CONSTRAINTS;
DROP TABLE 이호진 CASCADE CONSTRAINTS;
DROP TABLE 김동욱 CASCADE CONSTRAINTS;
DROP TABLE MEMBER_RECOMMEND CASCADE CONSTRAINTS;
DROP TABLE FAVORITE CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE BULLETIN CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

/**********************************/
/* Table Name: 회원 */
/**********************************/
CREATE TABLE MEMBER(
		MEMBERNO                      		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		ID                            		VARCHAR2(20)		 NULL ,
		PW                            		VARCHAR2(15)		 NULL ,
		MNAME                         		VARCHAR2(20)		 NULL ,
		MAREA                         		VARCHAR2(20)		 NULL 
);

COMMENT ON TABLE MEMBER is '회원';
COMMENT ON COLUMN MEMBER.MEMBERNO is '회원 번호';
COMMENT ON COLUMN MEMBER.ID is '아이디';
COMMENT ON COLUMN MEMBER.PW is '패스워드';
COMMENT ON COLUMN MEMBER.MNAME is '회원명';
COMMENT ON COLUMN MEMBER.MAREA is '거주지역';


/**********************************/
/* Table Name: 커뮤니티 */
/**********************************/
CREATE TABLE BULLETIN(
		BULLETINNUM                   		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		BULLETINNAME                  		VARCHAR2(200)		 NOT NULL,
		TEXT                          		VARCHAR2(500)		 NULL ,
		BULLETINPICTURE               		VARCHAR2(500)		 NULL 
);

DROP SEQUENCE BULLETIN_BULLETINNUM_SEQ;

CREATE SEQUENCE BULLETIN_BULLETINNUM_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER BULLETIN_BULLETINNUM_TRG
BEFORE INSERT ON BULLETIN
FOR EACH ROW
BEGIN
IF :NEW.BULLETINNUM IS NOT NULL THEN
  SELECT BULLETIN_BULLETINNUM_SEQ.NEXTVAL INTO :NEW.BULLETINNUM FROM DUAL;
END IF;
END;

COMMENT ON TABLE BULLETIN is '커뮤니티';
COMMENT ON COLUMN BULLETIN.BULLETINNUM is '커뮤니티 번호';
COMMENT ON COLUMN BULLETIN.BULLETINNAME is '제목';
COMMENT ON COLUMN BULLETIN.TEXT is '내용';
COMMENT ON COLUMN BULLETIN.BULLETINPICTURE is '사진';


/**********************************/
/* Table Name: 댓글 */
/**********************************/
CREATE TABLE REPLY(
		REPLYNO                       		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		MEMBERNO                      		NUMBER(10)		 NULL ,
		BULLETINNUM                   		NUMBER(10)		 NULL ,
		REPLYTEXT                     		VARCHAR2(500)		 DEFAULT .		 NOT NULL,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
  FOREIGN KEY (BULLETINNUM) REFERENCES BULLETIN (BULLETINNUM)
);

DROP SEQUENCE REPLY_REPLYNO_SEQ;

CREATE SEQUENCE REPLY_REPLYNO_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER REPLY_REPLYNO_TRG
BEFORE INSERT ON REPLY
FOR EACH ROW
BEGIN
IF :NEW.REPLYNO IS NOT NULL THEN
  SELECT REPLY_REPLYNO_SEQ.NEXTVAL INTO :NEW.REPLYNO FROM DUAL;
END IF;
END;

COMMENT ON TABLE REPLY is '댓글';
COMMENT ON COLUMN REPLY.REPLYNO is '댓글 번호';
COMMENT ON COLUMN REPLY.MEMBERNO is '회원 번호';
COMMENT ON COLUMN REPLY.BULLETINNUM is '커뮤니티 번호';
COMMENT ON COLUMN REPLY.REPLYTEXT is '댓글내용';


/**********************************/
/* Table Name: 관리자 */
/**********************************/
CREATE TABLE ADMIN(
		ADMINNO                       		NUMBER(5)		 NOT NULL		 PRIMARY KEY,
		ID                            		VARCHAR2(20)		 NOT NULL,
		PASSWD                        		VARCHAR2(15)		 NOT NULL,
		MNAME                         		VARCHAR2(20)		 NOT NULL,
		MDATE                         		DATE		 NOT NULL,
		GRADE                         		NUMBER(2)		 NOT NULL,
  CONSTRAINT SYS_C007060 UNIQUE (ID)
);

COMMENT ON TABLE ADMIN is '관리자';
COMMENT ON COLUMN ADMIN.ADMINNO is '관리자 번호';
COMMENT ON COLUMN ADMIN.ID is '아이디';
COMMENT ON COLUMN ADMIN.PASSWD is '패스워드';
COMMENT ON COLUMN ADMIN.MNAME is '성명';
COMMENT ON COLUMN ADMIN.MDATE is '가입일';
COMMENT ON COLUMN ADMIN.GRADE is '등급';


/**********************************/
/* Table Name: 유기동물 공고 데이터 */
/**********************************/
CREATE TABLE NOTICE(
		NOTICESNO                     		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		NOTICENUMBER                  		NUMBER(10)		 NOT NULL,
		IMAGEURL                      		VARCHAR2(100)		 NULL ,
		RECEIPTDATE                   		DATE		 NULL ,
		STATE                         		VARCHAR2(20)		 NULL ,
		PUBLICNOTICESTART             		DATE		 NULL ,
		PUBLICNOTICEEND               		DATE		 NULL ,
		ORGIDX                        		NUMBER(10)		 NULL ,
		SPECIES                       		VARCHAR2(15)		 NOT NULL,
		GENDER                        		CHAR(1)		 NOT NULL,
		DISCOVERYPLACE                		VARCHAR2(50)		 NOT NULL,
		CHARACTERISTIC                		VARCHAR2(50)		 NULL ,
		COLORCD                       		VARCHAR2(20)		 NOT NULL,
		AGE                           		VARCHAR2(10)		 NOT NULL,
		WEIGHT                        		VARCHAR2(10)		 NOT NULL,
		ORGNM                         		VARCHAR2(50)		 NULL ,
		CAREADDR                      		VARCHAR2(50)		 NULL ,
		OFFICETEL                     		VARCHAR2(20)		 NULL ,
		CARENM                        		VARCHAR2(20)		 NULL 
);

DROP SEQUENCE NOTICE_NOTICESNO_SEQ;

CREATE SEQUENCE NOTICE_NOTICESNO_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER NOTICE_NOTICESNO_TRG
BEFORE INSERT ON NOTICE
FOR EACH ROW
BEGIN
IF :NEW.NOTICESNO IS NOT NULL THEN
  SELECT NOTICE_NOTICESNO_SEQ.NEXTVAL INTO :NEW.NOTICESNO FROM DUAL;
END IF;
END;

COMMENT ON TABLE NOTICE is '유기동물 공고 데이터';
COMMENT ON COLUMN NOTICE.NOTICESNO is '컨텐츠 번호';
COMMENT ON COLUMN NOTICE.NOTICENUMBER is '공고번호';
COMMENT ON COLUMN NOTICE.IMAGEURL is '이미지';
COMMENT ON COLUMN NOTICE.RECEIPTDATE is '공고접수일';
COMMENT ON COLUMN NOTICE.STATE is '공고 상태';
COMMENT ON COLUMN NOTICE.PUBLICNOTICESTART is '공고 시작일';
COMMENT ON COLUMN NOTICE.PUBLICNOTICEEND is '공고 종료예정일';
COMMENT ON COLUMN NOTICE.ORGIDX is '보호기관 고유값';
COMMENT ON COLUMN NOTICE.SPECIES is '유기동물 종';
COMMENT ON COLUMN NOTICE.GENDER is '유기동물 성별';
COMMENT ON COLUMN NOTICE.DISCOVERYPLACE is '유기동물 발견장소';
COMMENT ON COLUMN NOTICE.CHARACTERISTIC is '유기동물 특징';
COMMENT ON COLUMN NOTICE.COLORCD is '유기동물 색깔';
COMMENT ON COLUMN NOTICE.AGE is '유기동물 탄생년도';
COMMENT ON COLUMN NOTICE.WEIGHT is '유기동물 몸무게';
COMMENT ON COLUMN NOTICE.ORGNM is '보호기관 관할';
COMMENT ON COLUMN NOTICE.CAREADDR is '보호기관 주소 ';
COMMENT ON COLUMN NOTICE.OFFICETEL is '보호기관 전화번호';
COMMENT ON COLUMN NOTICE.CARENM is '보호기관 시설명';


/**********************************/
/* Table Name: 즐겨찾기 */
/**********************************/
CREATE TABLE FAVORITE(
		MEMBERNO                      		INTEGER(10)		 NOT NULL		 PRIMARY KEY,
		NOTICESNO                     		NUMBER(10)		 NULL ,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
  FOREIGN KEY (NOTICESNO) REFERENCES NOTICE (NOTICESNO)
);

COMMENT ON TABLE FAVORITE is '즐겨찾기';
COMMENT ON COLUMN FAVORITE.MEMBERNO is '회원번호';
COMMENT ON COLUMN FAVORITE.NOTICESNO is '컨텐츠 번호';


/**********************************/
/* Table Name: 회원별 추천 유기동물 종 */
/**********************************/
CREATE TABLE MEMBER_RECOMMEND(
		RECOMMENDNO                   		INTEGER(10)		 NOT NULL		 PRIMARY KEY,
		MEMBERNO                      		NUMBER(10)		 NOT NULL,
		NOTICESNO                     		NUMBER(10)		 NOT NULL,
		RESULT                        		NUMBER(2)		 NOT NULL,
		RDATE                         		DATE		 NOT NULL,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
  FOREIGN KEY (NOTICESNO) REFERENCES NOTICE (NOTICESNO)
);

DROP SEQUENCE MEMBER_RECOMMEND_RECOMMENDNO_SEQ;

CREATE SEQUENCE MEMBER_RECOMMEND_RECOMMENDNO_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER MEMBER_RECOMMEND_RECOMMENDNO_TRG
BEFORE INSERT ON MEMBER_RECOMMEND
FOR EACH ROW
BEGIN
IF :NEW.RECOMMENDNO IS NOT NULL THEN
  SELECT MEMBER_RECOMMEND_RECOMMENDNO_SEQ.NEXTVAL INTO :NEW.RECOMMENDNO FROM DUAL;
END IF;
END;

COMMENT ON TABLE MEMBER_RECOMMEND is '회원별 추천 유기동물 종';
COMMENT ON COLUMN MEMBER_RECOMMEND.RECOMMENDNO is '추천번호';
COMMENT ON COLUMN MEMBER_RECOMMEND.MEMBERNO is '회원번호';
COMMENT ON COLUMN MEMBER_RECOMMEND.NOTICESNO is '컨텐츠 번호';
COMMENT ON COLUMN MEMBER_RECOMMEND.RESULT is '추천 우선순위';
COMMENT ON COLUMN MEMBER_RECOMMEND.RDATE is '추천일';


/**********************************/
/* Table Name: 김동욱 */
/**********************************/
CREATE TABLE 김동욱(

);

COMMENT ON TABLE 김동욱 is '김동욱';


/**********************************/
/* Table Name: 이호진 */
/**********************************/
CREATE TABLE 이호진(

);

COMMENT ON TABLE 이호진 is '이호진';


/**********************************/
/* Table Name: 채팅 */
/**********************************/
CREATE TABLE CHATTING(
		CHATTINGNO                    		NUMBER(8)		 NOT NULL		 PRIMARY KEY,
		MEMBERNO                      		NUMBER(10)		 NULL ,
		MSG                           		VARCHAR2(300)		 NOT NULL,
		RDATE                         		DATE		 NOT NULL,
		ISQUES                        		CHAR(2)		 DEFAULT T		 NULL ,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO)
);

DROP SEQUENCE CHATTING_CHATTINGNO_SEQ;

CREATE SEQUENCE CHATTING_CHATTINGNO_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER CHATTING_CHATTINGNO_TRG
BEFORE INSERT ON CHATTING
FOR EACH ROW
BEGIN
IF :NEW.CHATTINGNO IS NOT NULL THEN
  SELECT CHATTING_CHATTINGNO_SEQ.NEXTVAL INTO :NEW.CHATTINGNO FROM DUAL;
END IF;
END;

COMMENT ON TABLE CHATTING is '채팅';
COMMENT ON COLUMN CHATTING.CHATTINGNO is '채팅 번호';
COMMENT ON COLUMN CHATTING.MEMBERNO is '회원 번호';
COMMENT ON COLUMN CHATTING.MSG is '채팅 메시지';
COMMENT ON COLUMN CHATTING.RDATE is '등록일';
COMMENT ON COLUMN CHATTING.ISQUES is '질문여부';


