DROP TABLE BULLETIN CASCADE CONSTRAINTS;

/**********************************/
/* Table Name: 게시글 */
/**********************************/
CREATE TABLE BULLETIN(
		BULLETINNUM                   		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		TEXT                          		VARCHAR2(500)		 NULL 
);

DROP SEQUENCE BULLETIN_BULLETINNUM_SEQ;

CREATE SEQUENCE BULLETIN_BULLETINNUM_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER BULLETIN_BULLETINNUM_TRG
BEFORE INSERT ON BULLETIN
FOR EACH ROW
BEGIN
IF :NEW.BULLETINNUM IS NOT NULL THEN
  SELECT BULLETIN_BULLETINNUM_SEQ.NEXTVAL INTO :NEW.BULLETINNUM FROM DUAL;
END IF;
END;

COMMENT ON TABLE BULLETIN is '게시글';
COMMENT ON COLUMN BULLETIN.BULLETINNUM is '게시글 번호';
COMMENT ON COLUMN BULLETIN.TEXT is '내용';