DROP TABLE 이호진 CASCADE CONSTRAINTS;
DROP TABLE 김동욱 CASCADE CONSTRAINTS;
DROP TABLE MEMBER_RECOMMEND CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE TABLE_9 CASCADE CONSTRAINTS;
DROP TABLE ORGANIZATION CASCADE CONSTRAINTS;
DROP TABLE FAVORITE CASCADE CONSTRAINTS;
DROP TABLE CONTENTS CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE BULLETIN CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

/**********************************/
/* Table Name: 회원 */
/**********************************/
CREATE TABLE MEMBER(
		MEMBERNO                      		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		ID                            		VARCHAR2(20)		 NULL ,
		PW                            		VARCHAR2(15)		 NULL ,
		MNAME                         		VARCHAR2(20)		 NULL ,
		MAREA                         		VARCHAR2(20)		 NULL 
);

COMMENT ON TABLE MEMBER is '회원';
COMMENT ON COLUMN MEMBER.MEMBERNO is '회원 번호';
COMMENT ON COLUMN MEMBER.ID is '아이디';
COMMENT ON COLUMN MEMBER.PW is '패스워드';
COMMENT ON COLUMN MEMBER.MNAME is '회원명';
COMMENT ON COLUMN MEMBER.MAREA is '거주지역';


/**********************************/
/* Table Name: 게시글 */
/**********************************/
CREATE TABLE BULLETIN(
		BULLETINIDX                   		INTEGER(10)		 NOT NULL		 PRIMARY KEY,
		BULLETINNAME                  		VARCHAR2(200)		 NOT NULL,
		BULLETINTEXT                  		VARCHAR2(500)		 NULL ,
		FILE1                         		VARCHAR2(100)		 NULL ,
		FILE1SAVED                    		VARCHAR2(100)		 NULL ,
		THUMB1                        		VARCHAR2(100)		 NULL ,
		SIZE1                         		NUMBER(10)		 DEFAULT 0		 NULL 
);

DROP SEQUENCE BULLETIN_BULLETINIDX_SEQ;

CREATE SEQUENCE BULLETIN_BULLETINIDX_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER BULLETIN_BULLETINIDX_TRG
BEFORE INSERT ON BULLETIN
FOR EACH ROW
BEGIN
IF :NEW.BULLETINIDX IS NOT NULL THEN
  SELECT BULLETIN_BULLETINIDX_SEQ.NEXTVAL INTO :NEW.BULLETINIDX FROM DUAL;
END IF;
END;

COMMENT ON TABLE BULLETIN is '게시글';
COMMENT ON COLUMN BULLETIN.BULLETINIDX is '게시글번호';
COMMENT ON COLUMN BULLETIN.BULLETINNAME is '제목';
COMMENT ON COLUMN BULLETIN.BULLETINTEXT is '내용';
COMMENT ON COLUMN BULLETIN.FILE1 is '메인이미지';
COMMENT ON COLUMN BULLETIN.FILE1SAVED is '실제메인이미지';
COMMENT ON COLUMN BULLETIN.THUMB1 is '메인이미지프리뷰';
COMMENT ON COLUMN BULLETIN.SIZE1 is '메인이미지크기';


/**********************************/
/* Table Name: 댓글 */
/**********************************/
CREATE TABLE REPLY(
		REPLYNO                       		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		MEMBERNO                      		NUMBER(10)		 NULL ,
		BULLETINIDX                   		INTEGER(10)		 NULL ,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
  FOREIGN KEY (BULLETINIDX) REFERENCES BULLETIN (BULLETINIDX)
);

COMMENT ON TABLE REPLY is '댓글';
COMMENT ON COLUMN REPLY.REPLYNO is '댓글 번호';
COMMENT ON COLUMN REPLY.MEMBERNO is '회원 번호';
COMMENT ON COLUMN REPLY.BULLETINIDX is '게시글번호';


/**********************************/
/* Table Name: 관리자 */
/**********************************/
CREATE TABLE ADMIN(
		ADMINNO                       		NUMBER(5)		 NOT NULL		 PRIMARY KEY,
		ID                            		VARCHAR2(20)		 NOT NULL,
		PASSWD                        		VARCHAR2(15)		 NOT NULL,
		MNAME                         		VARCHAR2(20)		 NOT NULL,
		MDATE                         		DATE		 NOT NULL,
		GRADE                         		NUMBER(2)		 NOT NULL,
  CONSTRAINT SYS_C007060 UNIQUE (ID)
);

COMMENT ON TABLE ADMIN is '관리자';
COMMENT ON COLUMN ADMIN.ADMINNO is '관리자 번호';
COMMENT ON COLUMN ADMIN.ID is '아이디';
COMMENT ON COLUMN ADMIN.PASSWD is '패스워드';
COMMENT ON COLUMN ADMIN.MNAME is '성명';
COMMENT ON COLUMN ADMIN.MDATE is '가입일';
COMMENT ON COLUMN ADMIN.GRADE is '등급';


/**********************************/
/* Table Name: 컨텐츠 */
/**********************************/
CREATE TABLE CONTENTS(
		CONTENTSNO                    		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		ADMINNO                       		NUMBER(10)		 NOT NULL,
		DATAIDX                       		NUMBER(10)		 NULL ,
  FOREIGN KEY (ADMINNO) REFERENCES ADMIN (ADMINNO)
);

DROP SEQUENCE CONTENTS_CONTENTSNO_SEQ;

CREATE SEQUENCE CONTENTS_CONTENTSNO_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER CONTENTS_CONTENTSNO_TRG
BEFORE INSERT ON CONTENTS
FOR EACH ROW
BEGIN
IF :NEW.CONTENTSNO IS NOT NULL THEN
  SELECT CONTENTS_CONTENTSNO_SEQ.NEXTVAL INTO :NEW.CONTENTSNO FROM DUAL;
END IF;
END;

COMMENT ON TABLE CONTENTS is '컨텐츠';
COMMENT ON COLUMN CONTENTS.CONTENTSNO is '컨텐츠 번호';
COMMENT ON COLUMN CONTENTS.ADMINNO is '관리자 번호';
COMMENT ON COLUMN CONTENTS.DATAIDX is '유기동물 고유번호';


/**********************************/
/* Table Name: 즐겨찾기 */
/**********************************/
CREATE TABLE FAVORITE(
		MEMBERNO                      		INTEGER(10)		 NOT NULL,
		CONTENTSNO                    		NUMBER(10)		 NOT NULL,
  PRIMARY KEY (MEMBERNO, CONTENTSNO),
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
  FOREIGN KEY (CONTENTSNO) REFERENCES CONTENTS (CONTENTSNO)
);

COMMENT ON TABLE FAVORITE is '즐겨찾기';
COMMENT ON COLUMN FAVORITE.MEMBERNO is '회원번호';
COMMENT ON COLUMN FAVORITE.CONTENTSNO is '컨텐츠 번호';


/**********************************/
/* Table Name: 보호기관 */
/**********************************/
CREATE TABLE ORGANIZATION(
		ORGIDX                        		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		ORGNM                         		VARCHAR2(50)		 NULL ,
		CAREADDR                      		VARCHAR2(50)		 NULL ,
		OFFICETEL                     		VARCHAR2(20)		 NULL ,
		CARENM                        		VARCHAR2(20)		 NULL 
);

DROP SEQUENCE ORGANIZATION_ORGIDX_SEQ;

CREATE SEQUENCE ORGANIZATION_ORGIDX_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER ORGANIZATION_ORGIDX_TRG
BEFORE INSERT ON ORGANIZATION
FOR EACH ROW
BEGIN
IF :NEW.ORGIDX IS NOT NULL THEN
  SELECT ORGANIZATION_ORGIDX_SEQ.NEXTVAL INTO :NEW.ORGIDX FROM DUAL;
END IF;
END;

COMMENT ON TABLE ORGANIZATION is '보호기관';
COMMENT ON COLUMN ORGANIZATION.ORGIDX is '보호기관 고유값';
COMMENT ON COLUMN ORGANIZATION.ORGNM is '보호기관 관할';
COMMENT ON COLUMN ORGANIZATION.CAREADDR is '보호기관 주소';
COMMENT ON COLUMN ORGANIZATION.OFFICETEL is '보호기관 전화번호';
COMMENT ON COLUMN ORGANIZATION.CARENM is '보호기관 시설명';


/**********************************/
/* Table Name: 유기동물 데이터 */
/**********************************/
CREATE TABLE TABLE_9(
		PETIDX                        		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		SPECIES                       		VARCHAR2(15)		 NOT NULL,
		GENDER                        		CHAR(1)		 NOT NULL,
		DISCOVERYPLACE                		VARCHAR2(50)		 NOT NULL,
		CHARACTERISTIC                		VARCHAR2(50)		 NULL ,
		COLORCD                       		VARCHAR2(20)		 NOT NULL,
		AGE                           		VARCHAR2(10)		 NOT NULL,
		WEIGHT                        		VARCHAR2(10)		 NOT NULL
);

DROP SEQUENCE TABLE_9_PETIDX_SEQ;

CREATE SEQUENCE TABLE_9_PETIDX_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER TABLE_9_PETIDX_TRG
BEFORE INSERT ON TABLE_9
FOR EACH ROW
BEGIN
IF :NEW.PETIDX IS NOT NULL THEN
  SELECT TABLE_9_PETIDX_SEQ.NEXTVAL INTO :NEW.PETIDX FROM DUAL;
END IF;
END;

COMMENT ON TABLE TABLE_9 is '유기동물 데이터';
COMMENT ON COLUMN TABLE_9.PETIDX is '유기동물 고유값';
COMMENT ON COLUMN TABLE_9.SPECIES is '유기동물 종';
COMMENT ON COLUMN TABLE_9.GENDER is '유기동물 성별';
COMMENT ON COLUMN TABLE_9.DISCOVERYPLACE is '유기동물 발견장소';
COMMENT ON COLUMN TABLE_9.CHARACTERISTIC is '유기동물 특징';
COMMENT ON COLUMN TABLE_9.COLORCD is '유기동물 색깔';
COMMENT ON COLUMN TABLE_9.AGE is '유기동물 탄생년도';
COMMENT ON COLUMN TABLE_9.WEIGHT is '유기동물 몸무게';


/**********************************/
/* Table Name: 유기동물 공고 데이터 */
/**********************************/
CREATE TABLE NOTICE(
		DATAIDX                       		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		CONTENTSNO                    		NUMBER(10)		 NULL ,
		NOTICENUMBER                  		NUMBER(10)		 NOT NULL,
		IMAGEURL                      		VARCHAR2(100)		 NULL ,
		RECEIPTDATE                   		DATE		 NULL ,
		STATE                         		VARCHAR2(20)		 NULL ,
		PUBLICNOTICESTART             		DATE		 NULL ,
		PUBLICNOTICEEND               		DATE		 NULL ,
		ORGIDX                        		NUMBER(10)		 NULL ,
		PETIDX                        		NUMBER(10)		 NULL ,
  FOREIGN KEY (CONTENTSNO) REFERENCES CONTENTS (CONTENTSNO),
  FOREIGN KEY (ORGIDX) REFERENCES ORGANIZATION (ORGIDX),
  FOREIGN KEY (PETIDX) REFERENCES TABLE_9 (PETIDX)
);

DROP SEQUENCE NOTICE_DATAIDX_SEQ;

CREATE SEQUENCE NOTICE_DATAIDX_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER NOTICE_DATAIDX_TRG
BEFORE INSERT ON NOTICE
FOR EACH ROW
BEGIN
IF :NEW.DATAIDX IS NOT NULL THEN
  SELECT NOTICE_DATAIDX_SEQ.NEXTVAL INTO :NEW.DATAIDX FROM DUAL;
END IF;
END;

COMMENT ON TABLE NOTICE is '유기동물 공고 데이터';
COMMENT ON COLUMN NOTICE.DATAIDX is '고유값';
COMMENT ON COLUMN NOTICE.CONTENTSNO is '컨텐츠 번호';
COMMENT ON COLUMN NOTICE.NOTICENUMBER is '공고번호';
COMMENT ON COLUMN NOTICE.IMAGEURL is '이미지';
COMMENT ON COLUMN NOTICE.RECEIPTDATE is '공고접수일';
COMMENT ON COLUMN NOTICE.STATE is '공고 상태';
COMMENT ON COLUMN NOTICE.PUBLICNOTICESTART is '공고 시작일';
COMMENT ON COLUMN NOTICE.PUBLICNOTICEEND is '공고 종료예정일';
COMMENT ON COLUMN NOTICE.ORGIDX is '보호기관 고유값';
COMMENT ON COLUMN NOTICE.PETIDX is '유기동물 고유값';


/**********************************/
/* Table Name: 회원별 추천 유기동물 종 */
/**********************************/
CREATE TABLE MEMBER_RECOMMEND(
		MEMBERNO                      		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		IMAGE                         		VARCHAR2(50)		 NULL ,
		RESULT                        		VARCHAR2(20)		 NULL ,
		RDATE                         		DATE		 NULL ,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO)
);

COMMENT ON TABLE MEMBER_RECOMMEND is '회원별 추천 유기동물 종';
COMMENT ON COLUMN MEMBER_RECOMMEND.MEMBERNO is '회원번호';
COMMENT ON COLUMN MEMBER_RECOMMEND.IMAGE is '입력 이미지';
COMMENT ON COLUMN MEMBER_RECOMMEND.RESULT is '추천 결과';
COMMENT ON COLUMN MEMBER_RECOMMEND.RDATE is '추천일';


/**********************************/
/* Table Name: 김동욱 */
/**********************************/
CREATE TABLE 김동욱(

);

COMMENT ON TABLE 김동욱 is '김동욱';


/**********************************/
/* Table Name: 이호진 */
/**********************************/
CREATE TABLE 이호진(

);

COMMENT ON TABLE 이호진 is '이호진';


