DROP TABLE NOTICE CASCADE CONSTRAINTS;

/**********************************/
/* Table Name: 유기동물 공고 데이터 */
/**********************************/
CREATE TABLE NOTICE(
		DATAIDX                       		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		CONTENTSNO                    		NUMBER(10)		 NULL ,
		NOTICENUMBER                  		NUMBER(10)		 NOT NULL,
		IMAGEURL                      		VARCHAR2(100)		 NULL ,
		RECEIPTDATE                   		DATE		 NULL ,
		STATE                         		VARCHAR2(20)		 NULL ,
		PUBLICNOTICESTART             		DATE		 NULL ,
		PUBLICNOTICEEND               		DATE		 NULL ,
		ORGIDX                        		NUMBER(10)		 NULL ,
		PETIDX                        		NUMBER(10)		 NULL ,
  FOREIGN KEY (CONTENTSNO) REFERENCES CONTENTS (CONTENTSNO),
  FOREIGN KEY (ORGIDX) REFERENCES ORGANIZATION (ORGIDX),
  FOREIGN KEY (PETIDX) REFERENCES PETDATA (PETIDX)
);

DROP SEQUENCE NOTICE_DATAIDX_SEQ;

CREATE SEQUENCE NOTICE_DATAIDX_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER NOTICE_DATAIDX_TRG
BEFORE INSERT ON NOTICE
FOR EACH ROW
BEGIN
IF :NEW.DATAIDX IS NOT NULL THEN
  SELECT NOTICE_DATAIDX_SEQ.NEXTVAL INTO :NEW.DATAIDX FROM DUAL;
END IF;
END;

COMMENT ON TABLE NOTICE is '유기동물 공고 데이터';
COMMENT ON COLUMN NOTICE.DATAIDX is '고유값';
COMMENT ON COLUMN NOTICE.CONTENTSNO is '컨텐츠 번호';
COMMENT ON COLUMN NOTICE.NOTICENUMBER is '공고번호';
COMMENT ON COLUMN NOTICE.IMAGEURL is '이미지';
COMMENT ON COLUMN NOTICE.RECEIPTDATE is '공고접수일';
COMMENT ON COLUMN NOTICE.STATE is '공고 상태';
COMMENT ON COLUMN NOTICE.PUBLICNOTICESTART is '공고 시작일';
COMMENT ON COLUMN NOTICE.PUBLICNOTICEEND is '공고 종료예정일';
COMMENT ON COLUMN NOTICE.ORGIDX is '보호기관 고유값';
COMMENT ON COLUMN NOTICE.PETIDX is '유기동물 고유값';