DROP TABLE PETDATA CASCADE CONSTRAINTS;

/**********************************/
/* Table Name: 유기동물 데이터 */
/**********************************/
CREATE TABLE PETDATA(
		PETIDX                        		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		SPECIES                       		VARCHAR2(15)		 NOT NULL,
		GENDER                        		CHAR(1)		 NOT NULL,
		DISCOVERYPLACE                		VARCHAR2(50)		 NOT NULL,
		CHARACTERISTIC                		VARCHAR2(50)		 NULL ,
		COLORCD                       		VARCHAR2(20)		 NOT NULL,
		AGE                           		VARCHAR2(10)		 NOT NULL,
		WEIGHT                        		VARCHAR2(10)		 NOT NULL
);

DROP SEQUENCE PETDATA_PETIDX_SEQ;

CREATE SEQUENCE PETDATA_PETIDX_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER PETDATA_PETIDX_TRG
BEFORE INSERT ON PETDATA
FOR EACH ROW
BEGIN
IF :NEW.PETIDX IS NOT NULL THEN
  SELECT PETDATA_PETIDX_SEQ.NEXTVAL INTO :NEW.PETIDX FROM DUAL;
END IF;
END;

COMMENT ON TABLE PETDATA is '유기동물 데이터';
COMMENT ON COLUMN PETDATA.PETIDX is '유기동물 고유값';
COMMENT ON COLUMN PETDATA.SPECIES is '유기동물 종';
COMMENT ON COLUMN PETDATA.GENDER is '유기동물 성별';
COMMENT ON COLUMN PETDATA.DISCOVERYPLACE is '유기동물 발견장소';
COMMENT ON COLUMN PETDATA.CHARACTERISTIC is '유기동물 특징';
COMMENT ON COLUMN PETDATA.COLORCD is '유기동물 색깔';
COMMENT ON COLUMN PETDATA.AGE is '유기동물 탄생년도';
COMMENT ON COLUMN PETDATA.WEIGHT is '유기동물 몸무게';