DROP TABLE CONTENTS CASCADE CONSTRAINTS;

/**********************************/
/* Table Name: 컨텐츠 */
/**********************************/
CREATE TABLE CONTENTS(
		CONTENTSNO                    		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		ADMINNO                       		NUMBER(10)		 NOT NULL,
		DATAIDX                       		NUMBER(10)		 NULL ,
  FOREIGN KEY (ADMINNO) REFERENCES ADMIN (ADMINNO)
);

DROP SEQUENCE CONTENTS_CONTENTSNO_SEQ;

CREATE SEQUENCE CONTENTS_CONTENTSNO_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

CREATE TRIGGER CONTENTS_CONTENTSNO_TRG
BEFORE INSERT ON CONTENTS
FOR EACH ROW
BEGIN
IF :NEW.CONTENTSNO IS NOT NULL THEN
  SELECT CONTENTS_CONTENTSNO_SEQ.NEXTVAL INTO :NEW.CONTENTSNO FROM DUAL;
END IF;
END;

COMMENT ON TABLE CONTENTS is '컨텐츠';
COMMENT ON COLUMN CONTENTS.CONTENTSNO is '컨텐츠 번호';
COMMENT ON COLUMN CONTENTS.ADMINNO is '관리자 번호';
COMMENT ON COLUMN CONTENTS.DATAIDX is '유기동물 고유번호';